### ISSUE TITLE
Feature Request: search organization repos

### ISSUE THREAD

**Issue by 94929** [chrisgrieser/gitfred#1]
### Feature Requested

Hi, thanks for the great work. I started using this project and so far so good.
I think add the following two options to this project would be great:
1. input github token via configure workflow of alfred ui
2. using the input access token, search organization repos

Do you have plan for this?
Thanks in advance.

### Checklist

- [X] The feature would be useful to more users than just me.

**Comment by chrisgrieser** [comment]
Hi, in the latest version, I added the ability to specify a `$GITHUB_TOKEN` via Alfred workflow configuration as an alternative to exporting it in your `.zshenv`: https://github.com/chrisgrieser/gitfred/releases/download/1.1.0/gitfred.alfredworkflow

For the organization repos, I am not too sure about it. Reason being, that I simply do not use GitHub organization, and are thus not familiar with what would be needed here. I am open to PRs adding support for that though.
