### ISSUE TITLE
[Bug]: doesn't return all my repos

### ISSUE THREAD

**Issue by learn2reid** [chrisgrieser/gitfred#2]
### Bug Description

not all repos are returned.

### Debugging Log

```Text
only about 20 are returned
```

### Workflow Configuration

![Screenshot-Alfred Preferences-2024-07-08-17 50](https://github.com/chrisgrieser/gitfred/assets/3036190/a1071371-7768-41af-aa27-551cc6a0b116)

### Checklist

- [X] I have [updated to the latest version](./releases/latest) of this workflow.
- [X] I am using Alfred 5. (Older versions are not supported anymore.)

**Comment by chrisgrieser** [comment]
Cannot reproduce. Using `learn2reid` as username, it returns 40+ repositories for me.

**Comment by learn2reid** [comment]
Does it only return public repos?

**Comment by learn2reid** [comment]
It works using this workflow https://github.com/edgarjs/alfred-github-repos

**Comment by chrisgrieser** [comment]
Yes, it returns only public repos.

**Comment by learn2reid** [comment]
ah that's the issue? can we use our private key to return private repos?

**Comment by chrisgrieser** [comment]
Yes that's the issue. Since you noted 20 repos being listed, but have 40+ public repos in your profile, I was not able to notice. 

No, listing private repos is currently not implemented in this workflow.
